#include "prefix/prefix.h"

#include "data-mov/mov.h"
#include "data-mov/xchg.h"
#include "data-mov/pop.h"
#include "data-mov/push.h"
#include "data-mov/leave.h"
#include "data-mov/cltd.h"
#include "data-mov/movext.h"


#include "arith/dec.h"
#include "arith/inc.h"
#include "arith/neg.h"
#include "arith/imul.h"
#include "arith/mul.h"
#include "arith/idiv.h"
#include "arith/div.h"
#include "arith/cmp.h"
#include "arith/sub.h"
#include "arith/add.h"
#include "arith/adc.h"
#include "arith/sbb.h"

#include "logic/and.h"
#include "logic/or.h"
#include "logic/not.h"
#include "logic/xor.h"
#include "logic/sar.h"
#include "logic/shl.h"
#include "logic/shr.h"
#include "logic/shrd.h"
#include "logic/test.h"
#include "logic/setne.h"

#include "string/rep.h"
#include "string/movs.h"
#include "string/lods.h"
#include "string/scas.h"
#include "string/stos.h"

#include "misc/misc.h"

#include "special/special.h"

#include "control-transfer/call.h"
#include "control-transfer/je.h"
#include "control-transfer/jmp.h"
#include "control-transfer/jbe.h"
#include "control-transfer/ret.h"
#include "control-transfer/jne.h"
#include "control-transfer/jle.h"
#include "control-transfer/jg.h"
#include "control-transfer/jl.h"
#include "control-transfer/jge.h"
#include "control-transfer/js.h"
#include "control-transfer/jns.h"
#include "control-transfer/ja.h"